services:
  db:
    image: postgres:15-alpine
    container_name: db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file:
      - .env

volumes:
  db-data:
